name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install targets
        run: |
          rustup target add x86_64-unknown-linux-gnu
          rustup update nightly
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Build linux
        run: cargo build -Zbuild-std --target x86_64-unknown-linux-gnu --release 
      - name: test
        run: tree .
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload v0.1.0
          "target/x86_64-unknown-linux-gnu/release/hcc#Hcc for linux"
          --clobber
  build2:  
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install targets
        run: |
          rustup target add x86_64-pc-windows-msvc
          rustup update nightly
          rustup default nightly
          rustup component add rust-src --toolchain nightly-x86_64-pc-windows-msvc
      - name: Build windows
        run: cargo build -Zbuild-std --target x86_64-pc-windows-msvc --release --target-dir target/x86_64-pc-windows-msvc/release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload v0.1.0
          "target/x86_64-pc-windows-msvc/release/hcc.exe#Hcc for windows"
          --clobber
              
