name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install targets
        run: |
          rustup target add x86_64-pc-windows-msvc
          rustup target add x86_64-unknown-linux-gnu
          rustup update nightly
          rustup default nightly
      - name: Build windows
        run: cargo build --target x86_64-pc-windows-msvc
      - name: Build linux
        run: cargo build --target x86_64-unknown-linux-gnu
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release upload v0.1.0
          "output/hcc.exe#Hcc for windows"
          "output/hcc#Hcc for linux"
          --clobber
        
